package com.webapplication.crossport.controllers;

import com.webapplication.crossport.models.Article;
import com.webapplication.crossport.models.respository.ArticleRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;
import java.util.Optional;

@Controller
public class WebController
{

    @Autowired
    // This means to get the bean called userRepository. Which is
    // auto-generated by Spring, we will use it to handle the data
    private ArticleRepository articleRepository;

    @GetMapping(value = {"/", "/home", "/index.html"})
    public String greeting(HttpServletRequest request, @RequestParam(name =
            "name", required = false, defaultValue = "visitor") String name,
                           Model model)
    {
        model.addAttribute("name", name);

        HttpSession session = request.getSession(false);
        if(session == null){
            session = request.getSession(true);
        }

        return "index";
    }

    @GetMapping("/login")
    public String login(Model model)
    {

        return "login";
    }

    @GetMapping("/shop")
    public String shop(Model model)
    {

        Optional<Article> p = articleRepository.findById(1);

        p.ifPresent(article -> model.addAttribute("article", article));

        return "shop";
    }

}
