package com.webapplication.crossport.controllers;

import com.webapplication.crossport.models.Article;
import com.webapplication.crossport.models.repository.ArticleRepository;
import com.webapplication.crossport.models.Cart;
import com.webapplication.crossport.service.exception.CartException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;

import javax.servlet.http.HttpServletRequest;
import java.util.List;
import javax.servlet.http.HttpSession;
import java.util.Optional;

@Controller
public class WebController
{

    @Autowired
    // This means to get the bean called userRepository. Which is
    // auto-generated by Spring, we will use it to handle the data
    private ArticleRepository articleRepository;


    @GetMapping(value = {"/", "/home", "/index.html"})
    public String greeting(HttpServletRequest request, @RequestParam(name =
            "name", required = false, defaultValue = "visitor") String name,
                           Model model)
    {
        model.addAttribute("name", name);

        Cart cart = Cart.getCartInSession(request.getSession());
        try
        {
            cart.addToCart(1, 1);
            cart.addToCart(2, 2);
        }
        catch (CartException e)
        {
            e.printStackTrace();
        }


        return "index";
    }

    @GetMapping("/login")
    public String login(Model model)
    {

        return "login";
    }

    @GetMapping("/shop")
    public String shop(HttpServletRequest request, Model model)
    {

        Optional<Article> p = articleRepository.findById(1);

        p.ifPresent(article -> model.addAttribute("article", article));

        Cart cart = Cart.getCartInSession(request.getSession());

        if (p.isPresent())
        {
            model.addAttribute("product", p.get());
        }

        return "shop";
    }

    @GetMapping("/cart")
    public String cart(HttpServletRequest request, Model model)
    {
        return "cart";
    }

}
