# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: AWS deployment

on:
  push:
    branches: [ main ]


jobs:

  compile:
    runs-on: ubuntu-latest
    name: Running Java ${{ matrix.java }} compile
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Compile code
      run: mvn compile --file crossport/pom.xml

  deploy:
    runs-on: ubuntu-latest
    name: Deploy the JAR file to the remote server
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Generate the package
      run: mvn -B package --file crossport/pom.xml -D maven.test.skip=true
    - name: Write DMZ SSH Key 
      run: echo "${{ secrets.AMT_CROSSPORT_DMZ }}" > DMZ_KEY.pem && chmod 400 DMZ_KEY.pem
    - name: Start DMZ tunnel
      run: ssh -o StrictHostKeyChecking=no -L 23:${{ secrets.HOST }}:22 -L 8081:${{ secrets.HOST }}:8080 ${{ secrets.SSH_USER_DMZ }}@${{ secrets.HOST_DMZ }} -i DMZ_KEY.pem &
    - name: Write server SSH Key
      run: echo "${{ secrets.AMT_CROSSPORT }}" > KEY.pem && chmod 400 KEY.pem
    - name: Start server tunnel
      run: sudo ssh -o StrictHostKeyChecking=no -T ubuntu@localhost -p 23 -i KEY.pem &
