# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: AWS deployment

on:
  push:
    branches: [ main ]


jobs:

  compile:
    runs-on: ubuntu-latest
    name: Running Java ${{ matrix.java }} compile
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Compile code
      run: mvn compile

  deploy:
    runs-on: ubuntu-latest
    name: Deploy the JAR file to the remote server
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Generate the package
      run: mvn -B package --file pom.xml -D maven.test.skip=true
    - name: Write DMZ SSH Key
      run: echo "${{ secrets.AMT_CROSSPORT_DMZ }}" > DMZ_KEY.pem && chmod 400 DMZ_KEY.pem
    - name: Start DMZ tunnel
      run: ssh -tt -o StrictHostKeyChecking=no -L 8081:${{ secrets.HOST }}:8080 ${{ secrets.SSH_USER_DMZ }}@${{ secrets.HOST_DMZ }} -i DMZ_KEY.pem &
    - name: Deploy the package to the remote server
      uses: garygrossgarten/github-action-scp@release
      with:
        local: target/CrossportApp.war
        remote: /opt/tomcat/webapps/CrossportApp.war # My remote directory
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USER }}
        privateKey: ${{ secrets.AMT_CROSSPORT }}
